// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6Qzyhjq_HnDYHHGj_PcWIxq9sAxtNZTA',
    appId: '1:550231900255:web:395fdd764b2eec79b2dbea',
    messagingSenderId: '550231900255',
    projectId: 'maintenize',
    authDomain: 'maintenize.firebaseapp.com',
    storageBucket: 'maintenize.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKJnoBC3duDURP3a9JOJRaRIrwcgEGakI',
    appId: '1:550231900255:android:ff56a452fcfd5342b2dbea',
    messagingSenderId: '550231900255',
    projectId: 'maintenize',
    storageBucket: 'maintenize.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFQqhp-jaBD_BUMgKC_O6KMeXq-lubyyY',
    appId: '1:550231900255:ios:7aaed179c080a68fb2dbea',
    messagingSenderId: '550231900255',
    projectId: 'maintenize',
    storageBucket: 'maintenize.appspot.com',
    iosClientId: '550231900255-am2mjfmqjtjtbb2j4mrir1femkpkiu43.apps.googleusercontent.com',
    iosBundleId: 'com.aplanetbit.maintenize',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFQqhp-jaBD_BUMgKC_O6KMeXq-lubyyY',
    appId: '1:550231900255:ios:7aaed179c080a68fb2dbea',
    messagingSenderId: '550231900255',
    projectId: 'maintenize',
    storageBucket: 'maintenize.appspot.com',
    iosClientId: '550231900255-am2mjfmqjtjtbb2j4mrir1femkpkiu43.apps.googleusercontent.com',
    iosBundleId: 'com.aplanetbit.maintenize',
  );
}
